version: '3.8'

services:
  server:
    hostname: file-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8192:8192"
    volumes:
      - ./cmd/config.yaml:/cmd/config.yaml
      - ./storage:/storage